#!/bin/bash
#usage: ./submit_homework hw0

# Check if the number of arguments is not 1
if [ "$#" -ne 1 ]; then
    echo "Usage: ./submit_homework hw0"
    exit 1
fi

if [ ! -d "$1" ]; then
    echo "Error: homework directory does not exisit: $1"
    exist 1
fi

hwdir=/afs/umich.edu/user/j/i/jianghui/biostat625_submission/$USER

tar cz $1 > $1.tar.gz
cp $1.tar.gz hwdir

echo "Homework $1 submitted"



